//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant : Account
    {
        public int ApplicantId { get; set; }
        public string TrailHeadUrl { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
