//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int appId { get; set; }
        public string profileId { get; set; }
        public string status { get; set; }
        public int JobPosting_jobId { get; set; }
        public int Profile_profileId { get; set; }
    
        public virtual JobPosting JobPosting { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
