//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public int skillId { get; set; }
        public string skillName { get; set; }
        public int Badge_badgeId { get; set; }
    
        public virtual Badge Badge { get; set; }
    }
}
