//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemQuestions
    {
        public string skill { get; set; }
        public string userLevel { get; set; }
        public int Path_pathId { get; set; }
        public int Profile_profileId { get; set; }
        public int Badge_badgeId { get; set; }
        public int skill_id { get; set; }
    
        public virtual Path Path { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Badge Badge { get; set; }
    }
}
